import { CertifierApiClient } from "@oratlas/certifier-client";
import {
  CERTIFICATION_RESULT_SCHEMA_VERSION,
  ORA_SCIENTIFIC_MERIT_PROMPT_VERSION,
  ORA_SCIENTIFIC_MERIT_PROTOCOL_DEFINITION,
  deriveOraScientificMeritOutcome,
  publicationVersionPacketSchema,
  submitCertificationResultSchema,
  type PublicationVersionPacket,
} from "@oratlas/contracts";
import type {
  CertificationEvaluation,
  CertificationEvaluationExecutionMetadata,
  CertificationEvaluator,
} from "@oratlas/knowledge";

export const ORA_INDEPENDENCE_STATEMENT =
  "Assessment generated by the ORA reference certification service independently of the publication's declared production workflow.";

export interface OraExecutionRecorder {
  recordSucceeded(input: {
    packetSha256: string;
    packet: PublicationVersionPacket;
    evaluation: CertificationEvaluation;
    metadata: CertificationEvaluationExecutionMetadata;
  }): Promise<{ agentRunId: string; structuredOutputSha256: string }>;
}

export interface OraCertificationRequest {
  publicationVersionId: string;
  certificationProtocolId: string;
  idempotencyKey: string;
  externalRunReference?: string;
}

/** API-only ORA orchestration. This package has no database or application imports. */
export class OraCertificationService {
  constructor(
    private readonly client: CertifierApiClient,
    private readonly evaluator: CertificationEvaluator,
    private readonly recorder: OraExecutionRecorder,
  ) {}

  async certify(request: OraCertificationRequest) {
    const run = (await this.client.createRun({ ...request, assessmentMode: "ai" })) as {
      id: string;
      input: { packetSha256: string };
    };
    try {
      const frozen = (await this.client.getInput(run.id)) as {
        packetSha256: string;
        packet: unknown;
      };
      const packet = publicationVersionPacketSchema.parse(frozen.packet);
      if (frozen.packetSha256 !== run.input.packetSha256)
        throw new Error("CertificationRun input hash changed between creation and retrieval.");
      const evaluation = await this.evaluator.evaluate({
        packet,
        protocol: ORA_SCIENTIFIC_MERIT_PROTOCOL_DEFINITION,
      });
      if (evaluation.executionMetadata.promptVersion !== ORA_SCIENTIFIC_MERIT_PROMPT_VERSION) {
        throw new Error(
          "Evaluator prompt version does not match ORA Scientific Merit Pilot 0.1.0.",
        );
      }
      const outcome = deriveOraScientificMeritOutcome(
        evaluation.criteria,
        packet.completeness.content,
      );
      const recorded = await this.recorder.recordSucceeded({
        packetSha256: frozen.packetSha256,
        packet,
        evaluation,
        metadata: evaluation.executionMetadata,
      });
      if (recorded.structuredOutputSha256 !== evaluation.executionMetadata.structuredOutputSha256) {
        throw new Error(
          "Recorded execution output hash does not match the evaluator structured-output hash.",
        );
      }
      const candidate = submitCertificationResultSchema.parse({
        schemaVersion: CERTIFICATION_RESULT_SCHEMA_VERSION,
        packetSha256: frozen.packetSha256,
        criteria: evaluation.criteria,
        outcome,
        limitations: evaluation.limitations,
        conflictOfInterest: { status: "not-provided" },
        independence: { declared: true, statement: ORA_INDEPENDENCE_STATEMENT },
        provenance: {
          agentRunId: recorded.agentRunId,
          provider: evaluation.executionMetadata.provider,
          model: evaluation.executionMetadata.model,
          modelVersion: evaluation.executionMetadata.modelVersion,
          promptVersion: evaluation.executionMetadata.promptVersion,
          structuredOutputSha256: evaluation.executionMetadata.structuredOutputSha256,
        },
      });
      const result = await this.client.submitResult(run.id, candidate);
      return { run, input: { ...frozen, packet }, evaluation, outcome, result };
    } catch (error) {
      try {
        await this.client.transitionRun(run.id, {
          status: "failed",
          reason: boundedReason(error),
        });
      } catch (transitionError) {
        throw new AggregateError(
          [error, transitionError],
          "ORA evaluation failed and its run could not be transitioned to failed.",
        );
      }
      throw error;
    }
  }
}

export { CertifierApiClient };

function boundedReason(error: unknown) {
  const message = error instanceof Error ? error.message : "ORA evaluator failed.";
  return `ORA evaluator failed: ${message}`.slice(0, 4_000);
}
