import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const sourcePath = resolve(repoRoot, "docs/openapi.yaml");
export const artifactPath = resolve(repoRoot, "apps/web/src/generated/openapi-artifacts.ts");

type OpenApiDocument = {
  openapi?: unknown;
  info?: { title?: unknown; version?: unknown };
  paths?: unknown;
};

export function generateOpenApiArtifact(source: string): string {
  const yaml = source.replace(/\r\n?/g, "\n");
  const document = parse(yaml) as OpenApiDocument;
  if (
    typeof document?.openapi !== "string" ||
    typeof document.info?.title !== "string" ||
    typeof document.info.version !== "string" ||
    !document.paths ||
    typeof document.paths !== "object"
  ) {
    throw new Error("docs/openapi.yaml is missing required OpenAPI structure.");
  }

  const json = `${JSON.stringify(document, null, 2)}\n`;
  const yamlDigest = createHash("sha256").update(yaml).digest("hex");
  const jsonDigest = createHash("sha256").update(json).digest("hex");
  return (
    `// Generated by scripts/generate-openapi-artifacts.ts. Do not edit.\n` +
    `export const OPENAPI_YAML = ${JSON.stringify(yaml)};\n` +
    `export const OPENAPI_JSON = ${JSON.stringify(json)};\n` +
    `export const OPENAPI_YAML_ETAG = ${JSON.stringify(`"sha256-${yamlDigest}"`)};\n` +
    `export const OPENAPI_JSON_ETAG = ${JSON.stringify(`"sha256-${jsonDigest}"`)};\n`
  );
}

export function expectedOpenApiArtifact(): string {
  return generateOpenApiArtifact(readFileSync(sourcePath, "utf8"));
}

export function checkOpenApiArtifact(current: string): boolean {
  return current === expectedOpenApiArtifact();
}

function main(): void {
  const expected = expectedOpenApiArtifact();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(artifactPath, "utf8");
    } catch {
      // Report the same actionable drift message for a missing artifact.
    }
    if (current !== expected) {
      console.error("Generated OpenAPI artifacts are stale. Run: pnpm openapi:generate");
      process.exitCode = 1;
      return;
    }
    console.info("Generated OpenAPI artifacts match docs/openapi.yaml.");
    return;
  }

  writeFileSync(artifactPath, expected, "utf8");
  console.info("Generated apps/web/src/generated/openapi-artifacts.ts.");
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
