import { type KnowledgeIndexData } from "./types.js";

/** Two accepted reviews with overlapping evidence, for knowledge-layer tests. */
export const sampleIndex: KnowledgeIndexData = {
  reviews: [
    {
      reviewSlug: "replay-review",
      reviewId: "r1",
      reviewVersionId: "rv1",
      title: "Hippocampal Replay and Memory Consolidation",
      abstract: "Replay during sleep supports memory consolidation.",
      keywords: ["hippocampus", "replay", "memory"],
      domains: ["Neuroscience"],
      authors: ["Ada Rivera", "Kenji Watanabe"],
      acceptedAt: "2026-06-15T00:00:00Z",
      updatedAt: "2026-06-15T00:00:00Z",
      publicationYear: 2026,
      commitSha: "a".repeat(40),
      versionDoi: "10.5555/oratlas.example.replay",
      hasDoi: true,
      hasTrustData: true,
      hasEvidenceData: true,
      hasHumanReviewedTrust: true,
      compatibilityLevel: "compatible",
      status: "published",
    },
    {
      reviewSlug: "attention-review",
      reviewId: "r2",
      reviewVersionId: "rv2",
      title: "Cortical Oscillations and Selective Attention",
      abstract: "Gamma synchrony increases with attention.",
      keywords: ["attention", "gamma", "memory"],
      domains: ["Neuroscience"],
      authors: ["Lena Fischer"],
      acceptedAt: "2026-06-10T00:00:00Z",
      updatedAt: "2026-06-10T00:00:00Z",
      publicationYear: 2026,
      commitSha: "b".repeat(40),
      hasDoi: false,
      hasTrustData: true,
      hasEvidenceData: true,
      hasHumanReviewedTrust: false,
      compatibilityLevel: "partially-compatible",
      status: "published",
    },
  ],
  claims: [
    {
      claimId: "c-replay-1",
      reviewSlug: "replay-review",
      reviewId: "r1",
      reviewVersionId: "rv1",
      reviewTitle: "Hippocampal Replay and Memory Consolidation",
      text: "Sharp-wave ripple replay during sleep supports consolidation of spatial memory.",
      section: "Results",
      anchor: "sec-replay",
      claimType: "empirical",
      commitSha: "a".repeat(40),
      versionDoi: "10.5555/oratlas.example.replay",
      relations: [
        {
          citationId: "ref-shared",
          relationType: "supports",
          trust: {
            reviewStatus: "human-reviewed",
            aggregateScore: 0.82,
            aggregateMethod: "ordinal-mean-1.0",
            notableCriteria: ["entailment"],
          },
        },
      ],
    },
    {
      claimId: "c-replay-2",
      reviewSlug: "replay-review",
      reviewId: "r1",
      reviewVersionId: "rv1",
      reviewTitle: "Hippocampal Replay and Memory Consolidation",
      text: "Replay is strictly veridical reverse-order replay of the most recent trajectory.",
      section: "Discussion",
      claimType: "mechanistic",
      commitSha: "a".repeat(40),
      relations: [{ citationId: "ref-contra", relationType: "contradicts" }],
    },
    {
      claimId: "c-attn-1",
      reviewSlug: "attention-review",
      reviewId: "r2",
      reviewVersionId: "rv2",
      reviewTitle: "Cortical Oscillations and Selective Attention",
      text: "Coordinated neural activity supports memory-related cognitive performance.",
      section: "Results",
      claimType: "empirical",
      commitSha: "b".repeat(40),
      relations: [
        {
          citationId: "ref-shared",
          relationType: "supports",
          trust: {
            reviewStatus: "agent-proposed",
            notableCriteria: ["entailment"],
          },
        },
      ],
    },
  ],
  citations: [
    {
      citationId: "ref-shared",
      doi: "10.5555/oratlas.example.shared",
      title: "A shared source",
      year: 2000,
    },
    {
      citationId: "ref-contra",
      doi: "10.5555/oratlas.example.contra",
      title: "A contradicting source",
      year: 2010,
    },
  ],
};
